version: "3.8"
services:
  node1:
    image: blockchain
    container_name: node1
    network_mode: host
    command: -a 0.0.0.0:8080 -c i -n http://0.0.0.0:8081 -n http://0.0.0.0:8082
    ports:
      - 8080:8080
  node2:
    image: blockchain
    container_name: node2
    network_mode: host
    command: -a 0.0.0.0:8081 -c d -n http://0.0.0.0:8080 -n http://0.0.0.0:8082
    ports:
      - 8081:8081
  node3:
    image: blockchain
    container_name: node3
    network_mode: host
    command: -g -a 0.0.0.0:8082 -c r -n http://0.0.0.0:8080 -n http://0.0.0.0:8081
    ports:
      - 8082:8082